version: "3.7"

services:
  app_proxy:
    environment:
      # <app-id>_<service-name>_1  — строго так, с суффиксом _1
      APP_HOST: zuev-crafty_crafty-container_1
      APP_PORT: 8443               # внутренний HTTPS-порт Crafty
      APP_PROTOCOL: https          # ← ключевая строка
      PROXY_HTTPS_NO_VERIFY: "true"  # самоподписанный сертификат

  crafty-container:
    image: arcadiatechnology/crafty-4:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      TZ: Europe/Moscow
    # Порты для игровых серверов — оставлены как в оригинале
    ports:
      - "8443:8443"
      - "25500-25600:25500-25600"   # Java-серверы (TCP)
      - "19132:19132/udp"           # Bedrock-сервер (UDP)
    volumes:
      - ${APP_DATA_DIR}/backups:/crafty/backups
      - ${APP_DATA_DIR}/logs:/crafty/logs
      - ${APP_DATA_DIR}/servers:/crafty/servers
      - ${APP_DATA_DIR}/config:/crafty/app/config
      - ${APP_DATA_DIR}/import:/crafty/import