version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: zuev-crafty_crafty-container_1  # не трогаем
      APP_PORT: 8443                            # или 8000, если отключили SSL

  crafty-container:
    # container_name: crafty-container   ← ЭТУ строку удалить!
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: on-failure
    environment:
      TZ: Europe/Moscow
    ports:
      - "25500-25600:25500-25600"
      - "19132:19132/udp"
    volumes:
      - ${APP_DATA_DIR}/backups:/crafty/backups
      - ${APP_DATA_DIR}/logs:/crafty/logs
      - ${APP_DATA_DIR}/servers:/crafty/servers
      - ${APP_DATA_DIR}/config:/crafty/app/config
      - ${APP_DATA_DIR}/import:/crafty/import